a = int(input("Enter the first number: "))
b = int(input("Enter the second number: "))
print("Sum of the numbers is: ", a+b)
print("Difference of the numbers is: ", a-b)
print("Product of the numbers is: ", a*b)
